# Sandbox Tools Example
#
# Demonstrates the ListDirectory, WriteFile, ReadFile, and Shell tools
# with a Sandbox security configuration. The agent manages files in a
# temporary workspace with restricted permissions.
#
# Run with: mix run examples/sandbox_tools.exs

alias Agora.{AgentConfig, Message, ToolCall}
alias Agora.Tool.Sandbox

# Create a temporary workspace with starter files
workspace = Path.join(System.tmp_dir!(), "agora_sandbox_example_#{System.unique_integer([:positive])}")
File.mkdir_p!(workspace)
File.write!(Path.join(workspace, "notes.txt"), "Meeting at 3pm\nReview PR #42\nDeploy v2.1\n")
File.write!(Path.join(workspace, "data.csv"), "name,score\nAlice,95\nBob,87\nCarol,92\n")

try do
  # Configure sandbox with security boundaries
  sandbox = %Sandbox{
    working_directory: workspace,
    allowed_paths: [workspace],
    denied_commands: ["rm", "sudo", "chmod"],
    allow_shell_mode: false
  }

  # Counter-driven echo function for multi-turn tool calls
  counter = :counters.new(1, [:atomics])

  config = AgentConfig.new!(
    provider: :echo,
    model: "echo",
    instructions: "You are a file manager. Use tools to organize the workspace.",
    tools: [
      Agora.Tool.ListDirectory,
      Agora.Tool.WriteFile,
      Agora.Tool.ReadFile,
      Agora.Tool.Shell
    ],
    tool_opts: [sandbox: sandbox],
    provider_opts: [
      echo_mode: :function,
      echo_function: fn messages, _config ->
        count = :counters.get(counter, 1)
        :counters.add(counter, 1, 1)

        case count do
          0 ->
            # Turn 1: List directory contents
            {:ok,
             Message.assistant(nil, [
               ToolCall.new(%{
                 id: "call_1",
                 name: "list_directory",
                 arguments: %{"path" => "."}
               })
             ])}

          1 ->
            # Turn 2: Write a summary file
            {:ok,
             Message.assistant(nil, [
               ToolCall.new(%{
                 id: "call_2",
                 name: "write_file",
                 arguments: %{
                   "path" => "summary.txt",
                   "content" => "Workspace Summary\n=================\nGenerated by Agora agent\nFiles found: notes.txt, data.csv\n"
                 }
               })
             ])}

          2 ->
            # Turn 3: Read back the summary to verify
            {:ok,
             Message.assistant(nil, [
               ToolCall.new(%{
                 id: "call_3",
                 name: "read_file",
                 arguments: %{"path" => "summary.txt"}
               })
             ])}

          3 ->
            # Turn 4: Use shell to count lines in data.csv
            {:ok,
             Message.assistant(nil, [
               ToolCall.new(%{
                 id: "call_4",
                 name: "shell",
                 arguments: %{
                   "command" => "wc",
                   "args" => ["-l", "data.csv"]
                 }
               })
             ])}

          _ ->
            # Turn 5: Final summary referencing tool results
            tool_results =
              messages
              |> Enum.filter(&(&1.role == :tool))
              |> Enum.flat_map(& &1.tool_results)
              |> Enum.map(fn r -> "#{r.name}: #{inspect(r.content)}" end)
              |> Enum.join("\n  ")

            {:ok,
             Message.assistant(
               "Workspace organized! Here's what I did:\n" <>
                 "1. Listed directory contents\n" <>
                 "2. Created summary.txt\n" <>
                 "3. Verified the summary file\n" <>
                 "4. Counted lines in data.csv\n\n" <>
                 "Tool results:\n  #{tool_results}"
             )}
        end
      end
    ]
  )

  IO.puts("=== Sandbox Tools Example ===\n")
  IO.puts("Workspace: #{workspace}")
  IO.puts("Sandbox: allowed_paths=#{inspect(sandbox.allowed_paths)}, denied_commands=#{inspect(sandbox.denied_commands)}\n")
  IO.puts("User: Organize the workspace — list files, create a summary, and count data rows.\n")

  {:ok, response} = Agora.run(config, "Organize this workspace.")
  IO.puts("Agent: #{response.content}")
after
  # Clean up temporary workspace
  File.rm_rf!(workspace)
  IO.puts("\n(Cleaned up temporary workspace)")
end
